#!/bin/bash
# Run clean tests and print test-type summary after results.
cd "$(dirname "$0")"
echo "Building..."
dotnet build -q || exit 1
echo ""
echo "Running LUDO-T unit tests..."
echo ""
dotnet test LudoGame.Tests/LudoGame.Tests.csproj --no-build --logger "console;verbosity=normal"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              TEST TYPES IN THIS PROJECT                      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  ArchitectureTests (2)  — Factory pattern, Dependency Injection"
echo "  GameRulesTests (9)     — Unit tests for pure rule logic"
echo "  HomePathTests (9)      — Unit tests for home straight / Rule 10"
echo "  ApproachEntryTests (2) — Unit tests for CCW approach (T-1)"
echo "  GreenPlayerTests (1)   — Behaviour test for Green AI"
echo "  TestSuiteSummaryTests (1) — Prints this catalogue during test run"
echo ""
echo "  Total: 24 tests (23 rule/AI tests + 1 catalogue)"
echo ""
echo "See TEST_CASES.md for full descriptions of each test."
echo "Take a screenshot of the 'Passed: 24' line above for your report."
